import 'package:flutter/material.dart';

class  MyLocalizations {
  final Locale locale;

  MyLocalizations(this.locale);

  static Map<String, Map<String, String>> _localizedValuesMap = {
    'en_US': {
      'DRIVE': 'DRIVE',
      'EQ': 'EQ',
      'UPDATE': 'UPDATE',
      'INFO': 'INFO',
      'Warning': 'Warning',
      'No_fender_connected': 'No Fender F202 Connected.\nTry to connect?',
      'No': 'No Thanks',
      'OK': 'OK',
      'latest_firmware': 'latest firmware: ',
      'Firmware_Update': '   Firmware Update   ',
      'Firmware_updating': '   Firmware updating   ',
      'unknown':'checking',
      'update_failed': 'Update failed\nPlease try again later!',
      'Done': 'Done',
      'update_ok': 'Update finished.\nPlease connect it again!',
      'Audio_Enhance': 'Audio Enhance',
      'enhance_content': 'Audio enhance function allows fine tuning and power boosting of music playback',
      'Normal': 'Normal',
      'Fender': 'Fender',
      'Sezto': 'Sezto',
      'Electronic': 'Electronic',
      'Classical': 'Classical',
      'Female_Vocals': 'Female Vocals',
      'Monitor': 'Monitor',
      'Male_Vocals': 'Male Vocals',
      'Model':'Model',
      'Address':'Address',
      'Battery':'Battery',
      'Box battery':'Box battery',
      'Status':'Status',
      'Signal':'Signal',
      'Firmware':'Firmware',
      'App_Version':'App Version',

    },
    'zh_CN': {
      'DRIVE': '配置',
      'EQ': 'EQ',
      'UPDATE': '升级',
      'INFO': '资讯',
      'Warning': '警告',
      'No_fender_connected': '没有检测到fender F202.\n去连接?',
      'No': '不,谢谢',
      'OK': '是',
      'latest_firmware': '最新版本: ',
      'Firmware_Update': '   固件升级   ',
      'Firmware_updating': '   固件升级中   ',
      'unknown':'检查中',
      'update_failed': '升级失败\n请重试一下!',
      'Done': '完成',
      'update_ok': '升级成功.\n请重新连接耳机!',
      'Audio_Enhance': '音讯增强',
      'enhance_content': '音讯增强功能允许增强音乐播放的功率和微调。',
      'Normal': '普通',
      'Fender': 'Fender',
      'Sezto': 'Sezto',
      'Electronic': '电子音',
      'Classical': '古典',
      'Female_Vocals': '女声',
      'Monitor': '监听',
      'Male_Vocals': '男声',
      'Model':'型号',
      'Address':'序列号',
      'Battery':'电池',
      'Box battery':'耳机盒子',
      'Status':'充电状态',
      'Signal':'信号强度',
      'Firmware':'固件版本',
      'App_Version':'APP版本',
    },
    'zh_HK': {
      'DRIVE': '設定',
      'EQ': 'EQ',
      'UPDATE': '升級',
      'INFO': '資訊',
      'Warning': '警告',
      'No_fender_connected': '沒有檢測到fender F202.\n去連接?',
      'No': '不,謝謝',
      'OK': '好',
      'latest_firmware': '最新版本: ',
      'Firmware_Update': '   固件升級   ',
      'Firmware_updating': '   固件升級中   ',
      'unknown':'檢查中',
      'update_failed': '升級失敗\n請重試一下!',
      'Done': '完成',
      'update_ok': '升級成功.\n請重新連接耳機!',
      'Audio_Enhance': '音訊增強',
      'enhance_content': '音訊增強功能允許增強音樂播放的功率和微調。',
      'Normal': '普通',
      'Fender': 'Fender',
      'Sezto': 'Sezto',
      'Electronic': '電子音樂',
      'Classical': '古典',
      'Female_Vocals': '女聲',
      'Monitor': '監聽',
      'Male_Vocals': '男聲',
      'Model':'型號',
      'Address':'序號',
      'Battery':'電池',
      'Box battery':'耳機盒子',
      'Status':'充電狀態',
      'Signal':'信號强度',
      'Firmware':'固件版本',
      'App_Version':'APP版本',
    },
    'zh_TW': {
      'DRIVE': '設定',
      'EQ': 'EQ',
      'UPDATE': '升級',
      'INFO': '資訊',
      'Warning': '警告',
      'No_fender_connected': '沒有檢測到fender F202.\n去連接?',
      'No': '不,謝謝',
      'OK': '好',
      'latest_firmware': '最新版本: ',
      'Firmware_Update': '   固件升級   ',
      'Firmware_updating': '   固件升級中   ',
      'unknown':'檢查中',
      'update_failed': '升級失敗\n請重試一下!',
      'Done': '完成',
      'update_ok': '升級成功.\n請重新連接耳機!',
      'Audio_Enhance': '音訊增強',
      'enhance_content': '音訊增強功能允許增強音樂播放的功率和微調。',
      'Normal': '普通',
      'Fender': 'Fender',
      'Sezto': 'Sezto',
      'Electronic': '電子音樂',
      'Classical': '古典',
      'Female_Vocals': '女聲',
      'Monitor': '監聽',
      'Male_Vocals': '男聲',
      'Model':'型號',
      'Address':'序號',
      'Battery':'電池',
      'Box battery':'耳機盒子',
      'Status':'充電狀態',
      'Signal':'信號强度',
      'Firmware':'固件版本',
      'App_Version':'APP版本',
    }
  };

  String getText(String key){
    ///注意用 locale.toString()而非locale
    return _localizedValuesMap[locale.toString()][key];
  }

  get testText =>'abc';

  ///MyLocalizations的实例是在 Localizations中通过 MyLocalizationsDelegate实例化,
  ///应用中要使用 MyLocalizations的实例需要通过 Localizations这个 Widget来获取。
  static MyLocalizations of(BuildContext context){
    return Localizations.of(context, MyLocalizations);
  }
}