import 'package:flutter/material.dart';

class  MyLocalizations {
  final Locale locale;

  MyLocalizations(this.locale);

  static Map<String, Map<String, String>> _localizedValuesMap = {
    'en_US': {
      'DRIVE': 'DRIVE',
      'EQ': 'EQ',
      'UPDATE': 'UPDATE',
      'INFO': 'INFO',
      'Warning': 'Warning',
      'No_fender_connected': 'No Fender Tour Connected.\nTry to connect?',
      'No': 'No Thanks',
      'OK': 'OK',
      'latest_firmware': 'latest firmware: ',
      'Firmware_Update': '   Firmware Update   ',
      'Firmware_updating': '   Firmware updating   ',
      'unknown':'checking',
      'update_failed': 'Update failed\nPlease try again later!',
      'Done': 'Done',
      'update_ok': 'Update success.\nPlease connect it again!',
      'Audio_Enhance': 'Audio Enhance',
      'enhance_content': 'Audio enhance function allows fine tuning and power boosting of music playback',
      'Normal': 'Normal',
      'Fender': 'Fender',
      'Sezto': 'Original',
      'Electronic': 'Electronic',
      'Classical': 'Classical',
      'Female_Vocals': 'Female Vocals',
      'Monitor': 'Monitor',
      'Male_Vocals': 'Male Vocals',
      'Model':'Model',
      'Address':'Address',
      'Battery':'Battery',
      'Box battery':'Box battery',
      'Status':'Status',
      'Signal':'Signal',
      'Firmware':'Firmware',
      'App_Version':'App Version',
      'Enhance_describe':'  Adjust the power and intensity of your music playback. Select between Balanced and Ludicrous modes.',
      'model_describe':'  The model you connected is shown here.',
      'Eq_describe':'  Press the EQ icon to engage the equalizer. Adjust the frequencies to suit your liking.',
      'EqReset_describe':'  Press the "Reset" button to reset the EQ.',
      'Update_describe':'  Update your Fender Tour to the latest version of firmware by tapping here.',
      'Update_describe1':'  Press the “FIRMWARE UPDATE" button.',
      'Update_describe2':'  After the completion of firmware update, a dialog containing "Update success!" will pop up. Press "OK" to complete the process.',
      'Info_describe':'  Pressing the "INFO" icon displays the information of Fender Tour.',
      'Update_confirm':'Are you sure to update firmware ?',
      'Update':'Update',
      'Cancel':'Cancel',

    },
    'zh_CN': {
      'DRIVE': '配置',
      'EQ': 'EQ',
      'UPDATE': '升级',
      'INFO': '资讯',
      'Warning': '警告',
      'No_fender_connected': '没有检测到Fender Tour.\n去连接?',
      'No': '不,谢谢',
      'OK': '是',
      'latest_firmware': '最新版本: ',
      'Firmware_Update': '   固件升级   ',
      'Firmware_updating': '   固件升级中   ',
      'unknown':'检查中',
      'update_failed': '升级失败\n请重试一下!',
      'Done': '完成',
      'update_ok': '升级成功.\n请重新连接耳机!',
      'Audio_Enhance': '音讯增强',
      'enhance_content': '音讯增强功能允许增强音乐播放的功率和微调。',
      'Normal': '普通',
      'Fender': 'Fender',
      'Sezto': 'Original',
      'Electronic': '电子音',
      'Classical': '古典',
      'Female_Vocals': '女声',
      'Monitor': '监听',
      'Male_Vocals': '男声',
      'Model':'型号',
      'Address':'序列号',
      'Battery':'电池',
      'Box battery':'耳机盒子',
      'Status':'充电状态',
      'Signal':'信号强度',
      'Firmware':'固件版本',
      'App_Version':'APP版本',
      'Enhance_describe':'  调整音乐播放的功率和强度。在平衡模式和特殊模式之间进行选择。',
      'model_describe':'  此处显示当前连接的耳机。',
      'Eq_describe':'  按下EQ按钮使用均衡器。根据你的喜好调整频率。',
      'EqReset_describe':'  按下"复位"按钮复位EQ设置',
      'Update_describe':'  点击这里，把你的Fender Tour升级到最新版本的固件。',
      'Update_describe1':'  按下这个"固件升级"按钮。',
      'Update_describe2':'  固件升级完成后，会弹出一个显示"升级成功!"的对话框。点击"OK"来完成升级。',
      'Info_describe':'  按下"详情"按钮，会显示Fender Tour的详细信息。',
      'Update_confirm':'您确定要升级固件吗？',
      'Update':'升级',
      'Cancel':'取消',
    },
    'zh_HK': {
      'DRIVE': '設定',
      'EQ': 'EQ',
      'UPDATE': '升級',
      'INFO': '資訊',
      'Warning': '警告',
      'No_fender_connected': '沒有檢測到Fender Tour.\n去連接?',
      'No': '不,謝謝',
      'OK': '好',
      'latest_firmware': '最新版本: ',
      'Firmware_Update': '   固件升級   ',
      'Firmware_updating': '   固件升級中   ',
      'unknown':'檢查中',
      'update_failed': '升級失敗\n請重試一下!',
      'Done': '完成',
      'update_ok': '升級成功.\n請重新連接耳機!',
      'Audio_Enhance': '音訊增強',
      'enhance_content': '音訊增強功能允許增強音樂播放的功率和微調。',
      'Normal': '普通',
      'Fender': 'Fender',
      'Sezto': 'Original',
      'Electronic': '電子音樂',
      'Classical': '古典',
      'Female_Vocals': '女聲',
      'Monitor': '監聽',
      'Male_Vocals': '男聲',
      'Model':'型號',
      'Address':'序號',
      'Battery':'電池',
      'Box battery':'耳機盒子',
      'Status':'充電狀態',
      'Signal':'信號强度',
      'Firmware':'固件版本',
      'App_Version':'APP版本',
      'Enhance_describe':'  調整音樂播放的功率和强度。在平衡模式和特殊模式之間進行選擇。',
      'model_describe':'  此處顯示当前連接耳機。',
      'Eq_describe':'  按下EQ按鈕使用等化器。根據你的喜好調整頻率。',
      'EqReset_describe':'  按下"復位"按鈕復位EQ設定',
      'Update_describe':'  點擊這裡，把你的AE1i陞級到最新版本的固件。',
      'Update_describe1':'  按下這個"固件升級"按鈕。',
      'Update_describe2':'  固件升級完成後，會彈出一個顯示"陞級成功！"的對話方塊。點擊"OK"來完成陞級。',
      'Info_describe':'  按下"詳情"按鈕，會顯示Fender Tour的詳細資訊。',
      'Update_confirm':'您確定要陞級固件嗎？',
      'Update':'升級',
      'Cancel':'取消',
    },
    'zh_TW': {
      'DRIVE': '設定',
      'EQ': 'EQ',
      'UPDATE': '升級',
      'INFO': '資訊',
      'Warning': '警告',
      'No_fender_connected': '沒有檢測到Fender Tour.\n去連接?',
      'No': '不,謝謝',
      'OK': '好',
      'latest_firmware': '最新版本: ',
      'Firmware_Update': '   固件升級   ',
      'Firmware_updating': '   固件升級中   ',
      'unknown':'檢查中',
      'update_failed': '升級失敗\n請重試一下!',
      'Done': '完成',
      'update_ok': '升級成功.\n請重新連接耳機!',
      'Audio_Enhance': '音訊增強',
      'enhance_content': '音訊增強功能允許增強音樂播放的功率和微調。',
      'Normal': '普通',
      'Fender': 'Fender',
      'Sezto': 'Original',
      'Electronic': '電子音樂',
      'Classical': '古典',
      'Female_Vocals': '女聲',
      'Monitor': '監聽',
      'Male_Vocals': '男聲',
      'Model':'型號',
      'Address':'序號',
      'Battery':'電池',
      'Box battery':'耳機盒子',
      'Status':'充電狀態',
      'Signal':'信號强度',
      'Firmware':'固件版本',
      'App_Version':'APP版本',
      'Enhance_describe':'  調整音樂播放的功率和强度。在平衡模式和特殊模式之間進行選擇。',
      'model_describe':'  此處顯示当前連接耳機。',
      'Eq_describe':'  按下EQ按鈕使用等化器。根據你的喜好調整頻率。',
      'EqReset_describe':'  按下"復位"按鈕復位EQ設定',
      'Update_describe':'  點擊這裡，把你的AE1i陞級到最新版本的固件。',
      'Update_describe1':'  按下這個"固件升級"按鈕。',
      'Update_describe2':'  固件升級完成後，會彈出一個顯示"陞級成功！"的對話方塊。點擊"OK"來完成陞級。',
      'Info_describe':'  按下"詳情"按鈕，會顯示Fender Tour的詳細資訊。',
      'Update_confirm':'您確定要陞級固件嗎？',
      'Update':'升級',
      'Cancel':'取消',
    }
  };

  String getText(String key){
    ///注意用 locale.toString()而非locale
    return _localizedValuesMap[locale.toString()][key];
  }

  get testText =>'abc';

  ///MyLocalizations的实例是在 Localizations中通过 MyLocalizationsDelegate实例化,
  ///应用中要使用 MyLocalizations的实例需要通过 Localizations这个 Widget来获取。
  static MyLocalizations of(BuildContext context){
    return Localizations.of(context, MyLocalizations);
  }
}