import 'package:flutter/material.dart';

class  MyLocalizations {
  final Locale locale;

  MyLocalizations(this.locale);

  static Map<String, Map<String, String>> _localizedValuesMap = {
    'en_US': {
      'DRIVE': 'DRIVE',
      'EQ': 'EQ',
      'UPDATE': 'UPDATE',
      'INFO': 'INFO',
      'Warning': 'Warning',
      'No_fender_connected': 'No Fender Tour Connected.\nTry to connect?',
      'No': 'No Thanks',
      'OK': 'OK',
      'latest_firmware': 'latest firmware: ',
      'Firmware_Update': '   Firmware Update   ',
      'Firmware_updating': '   Firmware updating   ',
      'unknown':'checking',
      'update_failed': 'Update failed\nPlease try again later!',
      'Done': 'Done',
      'update_ok': '\nUpdate success.\n',
      'Audio_Enhance': 'Audio Enhance',
      'enhance_content': 'Audio enhance function allows fine tuning and power boosting of music playback',
      'high_gain':'High gain',
      'low_gain':'Low gain',
      'Normal': 'Original',
      'Fender': 'Fender',
      'Jazz': 'Jazz',
      'Rock': 'Rock',
      'Sezto': 'customize',
      'Electronic': 'Electronic',
      'Classical': 'Classical',
      'Female_Vocals': 'Female Vocals',
      'Monitor': 'Monitor',
      'Male_Vocals': 'Male Vocals',
      'Model':'Model',
      'Address':'Address',
      'Battery':'Battery',
      'Box battery':'Right side firmware',
      'Status':'Status',
      'Signal':'Signal',
      'Firmware':'Left side Firmware',
      'App_Version':'App Version',
      'Enhance_describe':'  Adjust the power and intensity of your music playback. Select between Balanced and Ludicrous modes.',
      'model_describe':'  The model you connected is shown here.',
      'Eq_describe':'  Press the EQ icon to engage the equalizer. Adjust the frequencies to suit your liking.',
      'EqReset_describe':'  Press the "Reset" button to reset the EQ.',
      'Update_describe':'  Update your Fender Tour to the latest version of firmware by tapping here.',
      'Update_describe1':'  Press the “FIRMWARE UPDATE" button.',
      'Update_describe2':'  After the completion of firmware update, a dialog containing "Update success!" will pop up. Press "OK" to complete the process.',
      'Info_describe':'  Pressing the "INFO" icon displays the information of Fender Tour.',
      'Update_confirm':'Are you sure to update firmware ?',
      'Update':'Update',
      'Cancel':'Cancel',
      'SETTING':'SETTING',
      'Reset':'Reset',
      'Updating_warn':'Please keep this screen foreground until update finished',
      'guide_overview':'Fender TOUR OverView',
      'Volume down':'Volume down',
      'Volume up':'Volume up',
      'Play/Pause':'Play/Pause',
      'PREV SONG':'PREV SONG',
      'Next Song':'Next Song',
      'None':'None',
      'Left tap':'Left tap',
      'Left double-tap':'Left double-tap',
      'Left hold':'Left hold',
      'Right tap':'Right tap',
      'Right double-tap':'Right double-tap',
      'Right hold':'Right hold',
      'firmware_updated':'Firmware is up to date!',
      'PAIRING':'PAIRING',
      'pairing_text0':'First time use, open the charging case, paired to your Phone.',
      'pairing_text1':'Second time use, open the charging case, press and hold the case button until the LED on the charging case blinks blue and green，the TWS LED blinks green.',
      'pairing_text2':'On your Bluetooth audio device, go to Bluetooth settings and select “Fender TOUR ”. Once connected, the TWS LED will turn off.',

      'CHARGING':'CHARGING',
      'charging_text1':'Close the lid and attach the USB-C charging cable to the charging case\n',
      'charging_text2':'The case LED will indicate the charging status: ',
      'charging_text3':'LED is solid red = Charging',
      'charging_text4':'LED is solid green = Fully charged',
      'UPGRADE':'Upgrade firmware',
      'upgrade_test1':'Left side:',
      'upgrade_test2':'Press the “Firmware Update” button, and keep this screen on the front until the upgrade finished.',
      'upgrade_test3':'Right side:',
      'upgrade_test4':'Open the charging case, press and hold the case button 15 second, until the LED on the charging case blinks blue, release the button. The right side blinks green.\n',
      'upgrade_test5':'On your Bluetooth audio device, go to Bluetooth settings and select “Fender TOUR R”. Once connected, the right side LED will turn off.\n',
      'upgrade_test6':'Back to the APP. Press the “Firmware Update” button, and keep this screen on the front until the upgrade finished.',
    },
    'zh_CN': {
      'DRIVE': '配置',
      'EQ': 'EQ',
      'UPDATE': '升级',
      'INFO': '资讯',
      'Warning': '警告',
      'No_fender_connected': '没有检测到Fender Tour.\n去连接?',
      'No': '不,谢谢',
      'OK': '是',
      'latest_firmware': '最新版本: ',
      'Firmware_Update': '   固件升级   ',
      'Firmware_updating': '   固件升级中   ',
      'unknown':'检查中',
      'update_failed': '升级失败\n请重试一下!',
      'Done': '完成',
      'update_ok': '\n升级成功.\n',
      'Audio_Enhance': '音讯增强',
      'enhance_content': '音讯增强功能允许增强音乐播放的功率和微调。',
      'high_gain':'高增益',
      'low_gain':'低增益',
      'Normal': '原声',
      'Fender': 'Fender',
      'Jazz': '爵士',
      'Rock': '摇滚',
      'Sezto': '自定义',
      'Electronic': '电子音',
      'Classical': '古典',
      'Female_Vocals': '女声',
      'Monitor': '监听',
      'Male_Vocals': '男声',
      'Model':'型号',
      'Address':'序列号',
      'Battery':'电池',
      'Box battery':'右边版本',
      'Status':'充电状态',
      'Signal':'信号强度',
      'Firmware':'左边版本',
      'App_Version':'APP版本',
      'Enhance_describe':'  调整音乐播放的功率和强度。在平衡模式和特殊模式之间进行选择。',
      'model_describe':'  此处显示当前连接的耳机。',
      'Eq_describe':'  按下EQ按钮使用均衡器。根据你的喜好调整频率。',
      'EqReset_describe':'  按下"复位"按钮复位EQ设置',
      'Update_describe':'  点击这里，把你的Fender Tour升级到最新版本的固件。',
      'Update_describe1':'  按下这个"固件升级"按钮。',
      'Update_describe2':'  固件升级完成后，会弹出一个显示"升级成功!"的对话框。点击"OK"来完成升级。',
      'Info_describe':'  按下"详情"按钮，会显示Fender Tour的详细信息。',
      'Update_confirm':'您确定要升级固件吗？',
      'Update':'升级',
      'Cancel':'取消',
      'SETTING':'设置',
      'Reset':'重置',
      'Updating_warn':'请保持此界面,等待升级完成',
      'guide_overview':'Fender TOUR 概览',
      'Volume down':'降低音量',
      'Volume up':'增大音量',
      'Play/Pause':'播放/暂停',
      'PREV SONG':'上一曲',
      'Next Song':'下一曲',
      'None':'无操作',
      'Left tap':'左边单击',
      'Left double-tap':'左边双击',
      'Left hold':'左边长按',
      'Right tap':'右边单击',
      'Right double-tap':'右边双击',
      'Right hold':'右边长按',
      'firmware_updated':'当前固件已是最新版本!',
      'PAIRING':'配对指引',
      'pairing_text0':'第一次使用时，打开盒子，左边耳机闪绿灯，就可以进行配对.',
      'pairing_text1':'第二次配对时，翻开充电盒上盖, 长按充电盒中间的按键2--7秒, 直到充电盒指示灯蓝绿交替闪烁松开，此时左边耳机会闪烁绿灯.',
      'pairing_text2':'在你的蓝牙音频设备的蓝牙设置界面, 点击选择“Fender TOUR”. 如果成功连接，左边指示灯将会熄灭.',

      'CHARGING':'充电指引',
      'charging_text1':'合上盖子, 将type-C充电线接入充电口\n',
      'charging_text2':'充电盒指示灯显示充电状态: ',
      'charging_text3':'指示灯亮红灯 = 充电中',
      'charging_text4':'指示灯亮绿灯 = 充满电',
      'UPGRADE':'耳机升级指引',
      'upgrade_test1':'左边:',
      'upgrade_test2':'按下 “固件升级” 按纽, 并保持升级界面在最前, 直到升级结束.',
      'upgrade_test3':'右边:',
      'upgrade_test4':'翻开充电盒上盖, 长按充电盒中间的按键15秒, 直到充电盒指示灯闪烁蓝色后松开, 此时右边耳机会闪烁绿灯.\n',
      'upgrade_test5':'在你的蓝牙音频设备的蓝牙设置界面, 点击选择“Fender TOUR R”. 如果成功连接, TWS指示灯将会熄灭.\n',
      'upgrade_test6':'返回APP, 按下 “固件升级” 按纽, 并保持升级界面在最前, 直到升级结束.',
    },
    'zh_HK': {
      'DRIVE': '設定',
      'EQ': 'EQ',
      'UPDATE': '升級',
      'INFO': '資訊',
      'Warning': '警告',
      'No_fender_connected': '沒有檢測到Fender Tour.\n去連接?',
      'No': '不,謝謝',
      'OK': '好',
      'latest_firmware': '最新版本: ',
      'Firmware_Update': '   固件升級   ',
      'Firmware_updating': '   固件升級中   ',
      'unknown':'檢查中',
      'update_failed': '升級失敗\n請重試一下!',
      'Done': '完成',
      'update_ok': '\n升級成功.\n',
      'Audio_Enhance': '音訊增強',
      'enhance_content': '音訊增強功能允許增強音樂播放的功率和微調。',
      'high_gain':'高增益',
      'low_gain':'低增益',
      'Normal': '原聲',
      'Fender': 'Fender',
      'Jazz': '爵士',
      'Rock': '搖滾',
      'Sezto': '自定義',
      'Electronic': '電子音樂',
      'Classical': '古典',
      'Female_Vocals': '女聲',
      'Monitor': '監聽',
      'Male_Vocals': '男聲',
      'Model':'型號',
      'Address':'序號',
      'Battery':'電池',
      'Box battery':'右邊版本',
      'Status':'充電狀態',
      'Signal':'信號强度',
      'Firmware':'左邊版本',
      'App_Version':'APP版本',
      'Enhance_describe':'  調整音樂播放的功率和强度。在平衡模式和特殊模式之間進行選擇。',
      'model_describe':'  此處顯示当前連接耳機。',
      'Eq_describe':'  按下EQ按鈕使用等化器。根據你的喜好調整頻率。',
      'EqReset_describe':'  按下"復位"按鈕復位EQ設定',
      'Update_describe':'  點擊這裡，把你的AE1i陞級到最新版本的固件。',
      'Update_describe1':'  按下這個"固件升級"按鈕。',
      'Update_describe2':'  固件升級完成後，會彈出一個顯示"陞級成功！"的對話方塊。點擊"OK"來完成陞級。',
      'Info_describe':'  按下"詳情"按鈕，會顯示Fender Tour的詳細資訊。',
      'Update_confirm':'您確定要陞級固件嗎？',
      'Update':'升級',
      'Cancel':'取消',
      'SETTING':'配置',
      'Reset':'重置',
      'Updating_warn':'請保持這個界面直到升級完成!',
      'guide_overview':'Fender TOUR 概覽',
      'Volume down':'降低音量',
      'Volume up':'增大音量',
      'Play/Pause':'播放/暂停',
      'PREV SONG':'上一曲',
      'Next Song':'下一曲',
      'None':'无操作',
      'Left tap':'左邊單擊',
      'Left double-tap':'左邊雙擊',
      'Left hold':'左邊長按',
      'Right tap':'右邊單擊',
      'Right double-tap':'右邊雙擊',
      'Right hold':'右邊長按',
      'firmware_updated':'当前固件已是最新版本!',
      'PAIRING':'配对指引',
      'pairing_text0':'第一次使用时，打开盒子，左边耳机闪绿灯，就可以进行配对.',
      'pairing_text1':'第二次配对时，翻开充电盒上盖, 长按充电盒中间的按键2--7秒, 直到充电盒指示灯蓝绿交替闪烁松开，此时左边耳机会闪烁绿灯.',
      'pairing_text2':'在你的蓝牙音频设备的蓝牙设置界面, 点击选择“Fender TOUR”. 如果成功连接，左边指示灯将会熄灭.',

      'CHARGING':'充电指引',
      'charging_text1':'合上盖子, 将type-C充电线接入充电口\n',
      'charging_text2':'充电盒指示灯显示充电状态: ',
      'charging_text3':'指示灯亮红灯 = 充电中',
      'charging_text4':'指示灯亮绿灯 = 充满电',
      'UPGRADE':'耳机升级指引',
      'upgrade_test1':'左边:',
      'upgrade_test2':'按下 “固件升级” 按纽, 并保持升级界面在最前, 直到升级结束.',
      'upgrade_test3':'右边:',
      'upgrade_test4':'翻开充电盒上盖, 长按充电盒中间的按键15秒, 直到充电盒指示灯闪烁蓝色后松开, 此时右边耳机会闪烁绿灯.\n',
      'upgrade_test5':'在你的蓝牙音频设备的蓝牙设置界面, 点击选择“Fender TOUR R”. 如果成功连接, TWS指示灯将会熄灭.\n',
      'upgrade_test6':'返回APP, 按下 “固件升级” 按纽, 并保持升级界面在最前, 直到升级结束.',
    },
    'zh_TW': {
      'DRIVE': '設定',
      'EQ': 'EQ',
      'UPDATE': '升級',
      'INFO': '資訊',
      'Warning': '警告',
      'No_fender_connected': '沒有檢測到Fender Tour.\n去連接?',
      'No': '不,謝謝',
      'OK': '好',
      'latest_firmware': '最新版本: ',
      'Firmware_Update': '   固件升級   ',
      'Firmware_updating': '   固件升級中   ',
      'unknown':'檢查中',
      'update_failed': '升級失敗\n請重試一下!',
      'Done': '完成',
      'update_ok': '\n升級成功.\n',
      'Audio_Enhance': '音訊增強',
      'enhance_content': '音訊增強功能允許增強音樂播放的功率和微調。',
      'high_gain':'高增益',
      'low_gain':'低增益',
      'Normal': '原聲',
      'Fender': 'Fender',
      'Jazz': '爵士',
      'Rock': '搖滾',
      'Sezto': '自定義',
      'Electronic': '電子音樂',
      'Classical': '古典',
      'Female_Vocals': '女聲',
      'Monitor': '監聽',
      'Male_Vocals': '男聲',
      'Model':'型號',
      'Address':'序號',
      'Battery':'電池',
      'Box battery':'右邊版本',
      'Status':'充電狀態',
      'Signal':'信號强度',
      'Firmware':'左邊版本',
      'App_Version':'APP版本',
      'Enhance_describe':'  調整音樂播放的功率和强度。在平衡模式和特殊模式之間進行選擇。',
      'model_describe':'  此處顯示当前連接耳機。',
      'Eq_describe':'  按下EQ按鈕使用等化器。根據你的喜好調整頻率。',
      'EqReset_describe':'  按下"復位"按鈕復位EQ設定',
      'Update_describe':'  點擊這裡，把你的AE1i陞級到最新版本的固件。',
      'Update_describe1':'  按下這個"固件升級"按鈕。',
      'Update_describe2':'  固件升級完成後，會彈出一個顯示"陞級成功！"的對話方塊。點擊"OK"來完成陞級。',
      'Info_describe':'  按下"詳情"按鈕，會顯示Fender Tour的詳細資訊。',
      'Update_confirm':'您確定要陞級固件嗎？',
      'Update':'升級',
      'Cancel':'取消',
      'SETTING':'配置',
      'Reset':'重置',
      'Updating_warn':'請保持這個界面直到升級完成!',
      'guide_overview':'Fender TOUR 概覽',
      'Volume down':'降低音量',
      'Volume up':'增大音量',
      'Play/Pause':'播放/暂停',
      'PREV SONG':'上一曲',
      'Next Song':'下一曲',
      'None':'无操作',
      'Left tap':'左邊單擊',
      'Left double-tap':'左邊雙擊',
      'Left hold':'左邊長按',
      'Right tap':'右邊單擊',
      'Right double-tap':'右邊雙擊',
      'Right hold':'右邊長按',
      'firmware_updated':'当前固件已是最新版本!',
      'PAIRING':'配对指引',
      'pairing_text0':'第一次使用时，打开盒子，左边耳机闪绿灯，就可以进行配对.',
      'pairing_text1':'第二次配对时，翻开充电盒上盖, 长按充电盒中间的按键2--7秒, 直到充电盒指示灯蓝绿交替闪烁松开，此时左边耳机会闪烁绿灯.',
      'pairing_text2':'在你的蓝牙音频设备的蓝牙设置界面, 点击选择“Fender TOUR”. 如果成功连接，左边指示灯将会熄灭.',

      'CHARGING':'充电指引',
      'charging_text1':'合上盖子, 将type-C充电线接入充电口\n',
      'charging_text2':'充电盒指示灯显示充电状态: ',
      'charging_text3':'指示灯亮红灯 = 充电中',
      'charging_text4':'指示灯亮绿灯 = 充满电',
      'UPGRADE':'耳机升级指引',
      'upgrade_test1':'左边:',
      'upgrade_test2':'按下 “固件升级” 按纽, 并保持升级界面在最前, 直到升级结束.',
      'upgrade_test3':'右边:',
      'upgrade_test4':'翻开充电盒上盖, 长按充电盒中间的按键15秒, 直到充电盒指示灯闪烁蓝色后松开, 此时右边耳机会闪烁绿灯.\n',
      'upgrade_test5':'在你的蓝牙音频设备的蓝牙设置界面, 点击选择“Fender TOUR R”. 如果成功连接, TWS指示灯将会熄灭.\n',
      'upgrade_test6':'返回APP, 按下 “固件升级” 按纽, 并保持升级界面在最前, 直到升级结束.',
    }
  };

  String getText(String key){
    ///注意用 locale.toString()而非locale
    return _localizedValuesMap[locale.toString()][key];
  }

  get testText =>'abc';

  ///MyLocalizations的实例是在 Localizations中通过 MyLocalizationsDelegate实例化,
  ///应用中要使用 MyLocalizations的实例需要通过 Localizations这个 Widget来获取。
  static MyLocalizations of(BuildContext context){
    return Localizations.of(context, MyLocalizations);
  }
}